### ISSUE TITLE
Exception thrown when all fields are valid

### ISSUE THREAD

**Issue by andycodecomplove** [tawashley/formalise#7]
Alright mate,

When every input is valid, I get an error here:

```
function focusOnFirstInvalidInput() {
    var firstInvalidInput = inputList.find(function (input) {
        return input.element.validity.valid === false;
    });
    firstInvalidInput.element.focus();
}
```
`firstInvalidInput` is undefined and it blows up. We're using version 1.2.0.

Is this a defect or am I using it incorrectly?

Cheers,
Andy

**Comment by tawashley** [comment]
Hey Andy,

You're right, this is an issue in the code. This has since been fixed with release https://github.com/tawashley/formalise/releases/tag/v2.0.5. Thanks for bringing this to my attention 😀👍

**Comment by andycodecomplove** [comment]
Thank you 🥇
